[package]
name = "makepassword"
version = "0.1.0"
authors = ["Hatter Jiang <jht5945@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
rand = "0.7.0"
rust_util = { git = "https://github.com/jht5945/rust_util" }
